Small jenkins changes
Change-Id: I585b2189622dc9cb0f4d2f7a5945e17a85c07e61

diff --git a/jenkins b/jenkins
--- a/jenkins
+++ b/jenkins
@@ -21,29 +21,29 @@ python manage.py jenkins \
 jenkins_status=$?
 grep -q "Your code has been rated at 10.00/10" reports/pylint.report
 pylint_status=$?
-! grep -q "py" reports/pep8.report
+grep -q "py" reports/pep8.report
 pep8_status=$?
 
-if [[ ($jenkins_status == 0) && ($pylint_status == 0) && ($pep8_status == 0) ]]; then
+if [[ ($jenkins_status == 0) && ($pylint_status == 0) && ($pep8_status != 0) ]]; then
     echo -e "\nEverything looks good!"
     exit 0
-fi
-
-if [[ $pylint_status != 0 ]]; then
-    echo -e "\nPYLINT VIOLATIONS"
-    echo "================================================================"
-    grep "^quark" reports/pylint.report
 else
-    echo -e "\nNo pylint violations."
-fi
+    if [[ $pylint_status != 0 ]]; then
+        echo -e "\nPYLINT VIOLATIONS"
+        echo "================================================================"
+        grep "^quark" reports/pylint.report
+    else
+        echo -e "\nNo pylint violations."
+    fi
 
-if [[ $pep8_status != 0 ]]; then
-    echo -e "\nPEP8 VIOLATIONS"
-    echo "================================================================"
-    cat reports/pep8.report
-else
-    echo -e "\nNo pep8 violations."
-fi
+    if [[ $pep8_status == 0 ]]; then
+        echo -e "\nPEP8 VIOLATIONS"
+        echo "================================================================"
+        cat reports/pep8.report
+    else
+        echo -e "\nNo pep8 violations."
+    fi
 
-echo -e "\nPlease fix all errors before doing git review!"
-exit 1
+    echo -e "\nPlease fix all errors before doing git review!"
+    exit 1
+fi
