parallelize and time run_tests
Change-Id: Ic894e8ce40f24a2bfb0fb3bbbc95dcdbafdfc22e

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -21,6 +21,8 @@ pushd $(dirname $0) > /dev/null
 # Clean up compiled python files
 find . -type f -name "*.py[co]" -delete
 
+# Cleanup old coverage runs
+rm -f .coverage
 # Remove old build reports:
 rm -rf reports
 # Make reports dir
@@ -29,6 +31,9 @@ mkdir -p reports
 # First ensure we have up-to-date submodules, as some may be required for tests:
 git submodule init
 git submodule update
+
+# Start timer
+start_time=$(date +"%s.%3N")
 
 # The following conditions must be true for test to pass:
 #   1. The tests must pass.
@@ -42,42 +47,77 @@ git submodule update
 # For full builds, pass in the "build" argument, which ensures that all desired
 # tasks are run
 if [[ $1 == 'build' ]]; then
-    rm -f .coverage
+    USE_COVERAGE=1
     # Run tests with coverage
-    coverage run manage.py test --settings=${PROJECT_NAME}.settings.test
-    # Error code should be 0 (no errors)
-    test_status=$?
-    # Generate text coverage report
-    coverage report > reports/coverage.report
+    TEST_RUNNER="coverage run"
 else
-    # Run tests directly with python
-    python manage.py test --settings=${PROJECT_NAME}.settings.test
-    # Error code should be 0 (no errors)
-    test_status=$?
+    USE_COVERAGE=0
+    TEST_RUNNER="python"
 fi
 
-# Check if pylint is perfect. Error code should be 0 (no errors)
-pylint --rcfile=.pylintrc ${PROJECT_NAME} > reports/pylint.report
-pylint_project_status=$?
-pylint --rcfile=.pylintrc scripts >> reports/pylint.report
-pylint_scripts_status=$?
+# Save exit status to a file for later parsing
+status_file="reports/status"
 
-# Check if pep8 is perfect. Error code should be 0 (no errors)
-# Exclude gitignore files by converting newlines to commas
-pep8 --config=.pep8rc \
-    --exclude=`sed -e :a -e 'N;s/\n/,/;ba' .gitignore` \
-    ${PROJECT_NAME} > reports/pep8.report
-pep8_status=$?
+# Run each test/check in its own subshell
+(
+    ${TEST_RUNNER} manage.py test --settings=${PROJECT_NAME}.settings.test
+    status=$?
+    if [[ ${USE_COVERAGE} == 1 ]]; then
+        # Generate text coverage report
+        coverage report > reports/coverage.report
+    fi
+    echo "test ${status}" >> ${status_file}
+) &
 
-# Check if jshint is perfect. Error code should be 0 (no errors)
-jshint --config .jshintrc quark/static/js/{main,slideshow,visual_datetime}.js \
-    > reports/jshint.report
-jshint_status=$?
+# Check if pylint for project is perfect. Exit code should be 0 (no errors)
+(
+    pylint --rcfile=.pylintrc ${PROJECT_NAME} > reports/pylint.report
+    echo "pylint_project $?" >> ${status_file}
+) &
 
-# Check if scss linting is perfect. Error code should be 0 (no errors)
-scss-lint ${PROJECT_NAME}/static/css/*.scss --config .scss-lint.yml \
-    > reports/scsslint.report
-scsslint_status=$?
+# Check if pylint for scripts is perfect. Exit code should be 0 (no errors)
+(
+    pylint --rcfile=.pylintrc scripts > reports/pylint_scripts.report
+    echo "pylint_scripts $?" >> ${status_file}
+) &
+
+# Check if pep8 is perfect. Exit code should be 0 (no errors)
+(
+    # Exclude gitignore files by converting newlines to commas
+    pep8 --config=.pep8rc \
+        --exclude=`sed -e :a -e 'N;s/\n/,/;ba' .gitignore` \
+        ${PROJECT_NAME} > reports/pep8.report
+    echo "pep8 $?" >> ${status_file}
+) &
+
+# Check if jshint is perfect. Exit code should be 0 (no errors)
+(
+    jshint --config .jshintrc \
+        ${PROJECT_NAME}/static/js/{main,slideshow,visual_datetime}.js \
+        > reports/jshint.report
+    echo "jshint $?" >> ${status_file}
+) &
+
+# Check if scss-lint is perfect. Exit code should be 0 (no errors)
+(
+    scss-lint ${PROJECT_NAME}/static/css/*.scss --config .scss-lint.yml \
+        > reports/scsslint.report
+    echo "scss-lint $?" >> ${status_file}
+) &
+
+# Wait for each checker to finish
+wait
+
+# Read their exit statuses
+test_status=$(grep test ${status_file} | cut -d ' ' -f 2)
+pylint_project_status=$(grep pylint_project ${status_file} | cut -d ' ' -f 2)
+pylint_scripts_status=$(grep pylint_scripts ${status_file} | cut -d ' ' -f 2)
+pep8_status=$(grep pep8 ${status_file} | cut -d ' ' -f 2)
+jshint_status=$(grep jshint ${status_file} | cut -d ' ' -f 2)
+scsslint_status=$(grep scss-lint ${status_file} | cut -d ' ' -f 2)
+
+# End timer
+end_time=$(date +"%s.%3N")
 
 if [[ $test_status == 0 ]] && \
    [[ $pylint_project_status == 0 ]] && \
@@ -96,6 +136,7 @@ else
         echo "================================================================"
         # Print until first blank line (the lines that say the errors)
         awk '/^\s*$/{exit}1' reports/pylint.report
+        awk '/^\s*$/{exit}1' reports/pylint_scripts.report
     else
         echo -e "\nNo pylint violations."
     fi
@@ -129,6 +170,10 @@ else
 
     echo -e "\nPlease fix all errors before doing git review!"
 fi
+
+# Report runtime
+duration=$(echo "$end_time - $start_time" | bc)
+echo "Total runtime: ${duration}s"
 
 popd > /dev/null
 exit $success
